"""Added required tables

Revision ID: a8b9f8ca9851
Revises: efb1f1b43c08
Create Date: 2023-06-04 18:38:33.201218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8b9f8ca9851'
down_revision = 'efb1f1b43c08'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
